service: collection-hello-world

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

custom:
  esbuild:
    bundle: true
    minify: true

package: 
  individually: true

functions:
  hello:
    handler: src/handler.hello
    events:
     - http:
        path: /hello
        method: get
